[package]
name = "solana-test-framework"
version = "1.0.2"
edition = "2021"
authors = ["lowprivuser"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
anchor = ["anchor-lang"]

[dependencies]
solana-program-test = "1.10"
solana-sdk = "1.10"
solana-program = "1.10"
solana-banks-client = "1.10"
spl-token = "3.3.0"
spl-associated-token-account = "1.0.5"
anchor-lang = { version = "0.25.0", optional = true }
async-trait = "0.1.52"
futures = "0.3"
borsh = "0.9"
bincode = "1.3.3"